language: java

jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6

notifications:
    email:
        - scm@after-sunrise.com

addons:
    hosts:
        - travis-hostname
    hostname: travis-hostname

after_success:
    - mvn site coveralls:report
